apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    app.kubernetes.io/name: proxmoxcluster
    app.kubernetes.io/instance: proxmoxcluster-sample
    app.kubernetes.io/part-of: cluster-api-provider-proxmox
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cluster-api-provider-proxmox
  name: proxmoxcluster-sample
spec:
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: ProxmoxCluster
    name: proxmoxcluster-sample