apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: proxmoxcluster-sample
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      controllerManager:
        extraArgs:
          enable-hostpath-provisioner: "true"
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
    postKubeadmCommands: []
    preKubeadmCommands: []
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: ProxmoxMachineTemplate
      name: proxmoxcluster-controlplane
  replicas: 1
  version: v1.26.5

---

apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: ProxmoxMachineTemplate
metadata:
  labels:
    app.kubernetes.io/name: proxmoxmachinetemplate
    app.kubernetes.io/instance: proxmoxcluster-controlplane
    app.kubernetes.io/part-of: cluster-api-provider-proxmox
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cluster-api-provider-proxmox
  name: proxmoxcluster-controlplane
spec:
  template:
    spec:
      # image:
      #   url: "dummy"
      cloudInit:
        user:
          user: ubnt
          password: ubnt
      ipConfig:
        gateway: 192.168.1.1
        ip: 192.168.1.222/32
