apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: proxmoxcluster-sample
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      etcd:
        local:
          dataDir: /var/lib/etcd
      networking:
        dnsDomain: cluster.local
        serviceSubnet: 10.96.0.0/12
        podSubnet: 10.98.0.0/16
    initConfiguration:
      localAPIEndpoint:
        advertiseAddress: 192.168.1.222  # your controlplane endpoint
        bindPort: 6443
      nodeRegistration:
        criSocket: unix:///var/run/containerd/containerd.sock
    postKubeadmCommands:
    - "curl -LO https://dl.k8s.io/release/v1.27.3/bin/linux/amd64/kubectl -o /usr/local/bin/kubectl"
    - "chmod +x /usr/lcoal/bin/kubectl"
    preKubeadmCommands: []
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: ProxmoxMachineTemplate
      name: proxmoxcluster-controlplane
  replicas: 1
  version: v1.26.5

---

apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: ProxmoxMachineTemplate
metadata:
  labels:
    app.kubernetes.io/name: proxmoxmachinetemplate
    app.kubernetes.io/instance: proxmoxcluster-controlplane
    app.kubernetes.io/part-of: cluster-api-provider-proxmox
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cluster-api-provider-proxmox
  name: proxmoxcluster-controlplane
spec:
  template:
    spec:
      image:
        url: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64-disk-kvm.img
      cloudInit:
        user:
          user: ubnt
          password: ubnt
      hardware:
        cpu: 4
        memory: 8192
      network:
        ipConfig:
          gateway: 192.168.1.1  # your gateway address
          ip: 192.168.1.222/32  # your controplane endpoint
        nameServer: 192.168.1.1  # your dns server address
      
