apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: proxmoxcluster-sample
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      controllerManager:
        extraArgs:
          enable-hostpath-provisioner: "true"
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
    postKubeadmCommands: []
    preKubeadmCommands: []
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: ProxmoxMachineTemplate
      name: proxmoxcluster-controlplane
  replicas: 1
  version: v1.21.2

---

# apiVersion: cluster.x-k8s.io/v1beta1
# kind: Machine
# metadata:
#   name: proxmoxcluster-controlplane
#   labels:
#     cluster.x-k8s.io/cluster-name: proxmoxcluster-sample
#     cluster.x-k8s.io/control-plane: "true"
# spec:
#   clusterName: proxmoxcluster-sample
#   infrastructureRef:
#     apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
#     kind: ProxmoxMachineTemplate
#     name: proxmoxcluster-controlplane
#   bootstrap:
#     configRef:
#       apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
#       kind: KubeadmConfig
#       name: proxmoxcluster-controlplane

---

apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: ProxmoxMachineTemplate
metadata:
  labels:
    app.kubernetes.io/name: proxmoxmachinetemplate
    app.kubernetes.io/instance: proxmoxcluster-controlplane
    app.kubernetes.io/part-of: cluster-api-provider-proxmox
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cluster-api-provider-proxmox
  name: proxmoxcluster-controlplane
spec:
  template:
    spec:
      providerID: ""
      failureDomain: ""

---

# apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
# kind: KubeadmConfig
# metadata:
#   name: proxmoxcluster-controlplane
# spec:
#   initConfiguration:
#     nodeRegistration:
#       kubeletExtraArgs:
#         eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
#   clusterConfiguration:
#     controllerManager:
#       extraArgs:
#         enable-hostpath-provisioner: "true"