apiVersion: cluster.x-k8s.io/v1beta1
kind: Machine
metadata:
  name: proxmoxmachine-sample
spec:
  clusterName: proxmoxcluster-sample
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: ProxmoxMachine
    name: proxmoxmachine-sample
  bootstrap:
    configRef:
      apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
      kind: KubeadmConfig
      name: proxmoxcluster-sample
    dataSecretName: "proxmoxcluster-sample-datasecret"