name: CI

on:
  push:
    branches:
    - main
  issue_comment:
    types: [created, edited]

env:
  REGISTRY: docker.io
  IMAGE_NAME: spyduck/cluster-api-provider-proxmox

jobs:
  # add public code coverage reports
  coverage:
    name: unit test coverage
    runs-on: ubuntu-latest
    if: github.event_name == "push" || contains(github.event.comment.body, "/unit-test")
    steps:
    - uses: actions/checkout@master
    - run: "make unit-test-cover"
    - uses: codecov/codecov-action@v2

  # build and push to docker.io
  build:
    name: docker build & push
    runs-on: ubuntu-latest
    if: github.event_name == "push" || contains(github.event.comment.body, "/buid-push")
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # platform = linux/amd64,linux/arm64
      - name: Build and push Docker image
        run: "make docker-buildx IMG=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${GITHUB_SHA::7}"