# add public code coverage reports
on:
  push:
    branches:
    - main
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: "make test-cover"
    - uses: codecov/codecov-action@v2